name: App - Build & Deploy Containers

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/Deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy App
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: project2-najla
      LOCATION: westeurope

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and push Frontend image
        run: |
          docker build -t $ACR_NAME.azurecr.io/frontend:latest ./frontend
          docker push $ACR_NAME.azurecr.io/frontend:latest

      - name: Build and push Backend image
        run: |
          docker build -t $ACR_NAME.azurecr.io/backend:latest ./backend
          docker push $ACR_NAME.azurecr.io/backend:latest

      - name: Deploy Containers
        run: |
          az containerapp update \
            --name project2-app \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/backend:latest
